/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      colors.h                                   ||
||     Author:    Autogenerated                              ||
||     Generated: 18.08.2022                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef IncludesFor_colors
#define IncludesFor_colors (1)


#define EMAC_CHAR ''
#define EMAC_STRG ""

const char* colors_string(const char* text,const char* emac);
const char* colors_select(const char* emac);

#ifdef _OnTheFly_
#include ".colors.cc"
#endif
#endif
