/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      hallo.h                                    ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef IncludesFor_hallo
#define IncludesFor_hallo (1)


#include ".environMentor.h"


#ifdef _OnTheFly_
#include ".hallo.cc"
#endif
#endif
