/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      softpass.h                                 ||
||     Author:    Autogenerated                              ||
||     Generated: 13.03.2022                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#ifndef IncludesFor_softpass
#define IncludesFor_softpass (1)

/*
const char* softpass_get( const char* ort );
const char* softpass_add( const char* ort, const char* xwort );
const char* softpass_rem( const char* ort );
const char* softpass_lst( void ); 
*/

const char* softpass_set_master( const char* oldkey, const char* newkey );
const char* softpass_set_folder( const char* phrase, const char* folder );
const char* softpass_set_crypte( const char* phrase, const char* crypte );


#ifdef _OnTheFly_
#include ".softpass.cc"
#endif
#endif
