#!/usr/bin/tcc -run -w
/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      autostart.c                                ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#define _OnTheFly_ autostart
#define autostart ""
#include ".autostart.h"
int main(int argc,char** argv);
