#!/usr/bin/tcc -run -w
/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      colors.c                                   ||
||     Author:    Autogenerated                              ||
||     Generated: 18.08.2022                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#define _OnTheFly_ colors
#define colors ""
#include ".colors.h"
int main(int argc,char** argv);
