#!/usr/bin/tcc -run -w
/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      hash64.c                                   ||
||     Author:    autogenerated                              ||
||     Generated: by Command Generator v.0.1                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#define _OnTheFly_ hash64
#define hash64 ""
#include ".hash64.h"
int main(int argc,char** argv);
