#!/usr/bin/tcc -run -w
/*///////////////////////////////////////////////////////////*\
||                                                           ||
||     File:      softpass.c                                 ||
||     Author:    Autogenerated                              ||
||     Generated: 13.03.2022                                 ||
||                                                           ||
\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*/
#define _OnTheFly_ softpass
#define softpass ""
#include ".softpass.h"
int main(int argc,char** argv);
