#define BASE64_CODING_TABLE "noTableWasPushed"
#define BASE64_PUSHED_TABLE "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="
#define BASE64_WITH_LINEBREAKS (0)
#define BASE64_REVERSED_ORDER (1)
#define BASE64_VERFAHREN (2)
///[base64Reflector]
#define NUMBER_OF_FEATURES (5)
const static int base64_NUMBER_OF_MACROS = NUMBER_OF_FEATURES;
const static char* FEATURE_NAMES[NUMBER_OF_FEATURES] = {
    "BASE64_CODING_TABLE\0\"noTableWasPushed\"",
    "BASE64_PUSHED_TABLE\0\"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=\"",
    "BASE64_WITH_LINEBREAKS\0(0)",
    "BASE64_REVERSED_ORDER\0(1)",
    "BASE64_VERFAHREN\0(2)",
};
