#define BASE64_REVERSED_ORDER (1)
#define BASE64_WITH_LINEBREAKS (0)
#define BASE64_VERFAHREN (1)
///[crypt64Reflector]
#define NUMBER_OF_FEATURES (3)
const static int crypt64_NUMBER_OF_MACROS = NUMBER_OF_FEATURES;
const static char* FEATURE_NAMES[NUMBER_OF_FEATURES] = {
    "BASE64_REVERSED_ORDER\0(1)",
    "BASE64_WITH_LINEBREAKS\0(0)",
    "BASE64_VERFAHREN\0(1)",
};
